Turn on the adjoint by default, but if the user doesn't want it, turn it off, or if he wants it but can't have it, complain, or if he wants it and it didn't link, complain, and ...

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -795,16 +795,32 @@ fi
 
 
 HAVE_ADJOINT=no
+CAN_USE_ADJOINT=yes
+WANTS_ADJOINT=yes
+if test "$USING_GFORTRAN" = "yes"; then # check gfortran version >= 4.5
+  # test really is so retarded that it can't lexicographically compare strings
+  if test "$(python -c "print \"$GFORTRAN_VERSION\" <= \"4.5\"")" = "True"; then
+    CAN_USE_ADJOINT=no
+  fi
+fi
+
+if test "$with_adjoint" = no || test -z "$with_adjoint"; then
+  WANTS_ADJOINT=no
+fi
+
+if test "$CAN_USE_ADJOINT" = "no" && test "$WANTS_ADJOINT" = "yes"; then
+  echo "Wanted adjoint, but you need gcc > 4.5"
+  exit 1
+fi
+
+echo "with_adjoint: " $with_adjoint
 if test "$with_adjoint" != "no"; then
-  if test ! -z "$with_adjoint"; then
-    HAVE_ADJOINT=yes
+  if test "$CAN_USE_ADJOINT" != "no"; then
     ACX_adjoint([AC_MSG_NOTICE(["libadjoint found"])], [AC_MSG_WARN(["libadjoint not found"])])
-    if test "$USING_GFORTRAN" = "yes"; then # check gfortran version >= 4.5
-      # test really is so retarded that it can't lexicographically compare strings
-      if test "$(python -c "print \"$GFORTRAN_VERSION\" <= \"4.5\"")" = "True"; then
-        AC_MSG_ERROR(["Need gfortran >= 4.5 for the adjoint, sorry"])
-      fi
-    fi
+  fi
+  if test "$HAVE_ADJOINT" = "no" && test "$WANTS_ADJOINT" = "yes"; then
+    echo "Wanted adjoint, but couldn't find it"
+    exit 1
   fi
 fi
 AC_SUBST(HAVE_ADJOINT)
