Make test from out-of-tree build.
This uses a symlink builddir/tests -> srcdir/tests and
srcdir/bin -> builddir/bin. The latter is necessary to make
all the ../../bin/foo stuff in the tests work.

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -464,6 +464,7 @@ clean-debian:
 
 clean-test:      
 	@echo "    CLEAN tests"
+	@if [ ! -d tests ]; then ln -s @srcdir@/tests/; fi
 	@cd tests; PYTHONPATH=../python ../tools/testharness.py --clean >/dev/null
 	@cd tests/data; $(MAKE) clean
 
@@ -516,9 +517,25 @@ distclean: clean
 test: fltools bin/$(FLUIDITY) bin/shallow_water serialtest bin/burgers_equation
 
 serialtest: fltools bin/$(FLUIDITY) bin/shallow_water
+	@if [ ! -d tests ]; then ln -s @srcdir@/tests/; fi
+	@if [ ! @srcdir@ -ef bin ]; then \
+	  if [ -e @srcdir@/bin ]; then \
+	    rm @srcdir@i/bin; \
+	  fi && ln -s $(CURDIR)/bin @srcdir@/bin || { echo "*** ERROR ***: @srcdir@ already exists. \
+You need to remove this directory before running make test from the current build directory. \
+It will be replaced by a symlink to bin/ in the current directory."; false; } \
+	fi
 	@cd tests; ../bin/testharness -l short $(EXCLUDE_TAGS) -n $(THREADS)
 
 mediumtest: fltools bin/$(FLUIDITY) manual bin/burgers_equation bin/shallow_water spudtools
+	@if [ ! -d tests ]; then ln -s @srcdir@/tests/; fi
+	@if [ ! @srcdir@ -ef bin ]; then \
+	  if [ -e @srcdir@/bin ]; then \
+	    rm @srcdir@i/bin; \
+	  fi && ln -s $(CURDIR)/bin @srcdir@/bin || { echo "*** ERROR ***: @srcdir@ already exists. \
+You need to remove this directory before running make test from the current build directory. \
+It will be replaced by a symlink to bin/ in the current directory."; false; } \
+	fi
 	@cd tests; ../bin/testharness -l medium $(EXCLUDE_TAGS) -n $(THREADS)
 
 .PHONY: spudtools
