Change configure scripts to allow out-of-tree builds.
This allows you to build fluidity in a separate directory (including all
object files and libraries), without touching any of the checked in source
directories at all. This makes it possible to switch between branches in
a git clone of fluidity without loosing the various associated builds.

Simply call configure from any directory (other than the fluidity top
directory). The Makefiles will then be created in a hierarchy of directories
created under the current directory. When running make subsequently all new
files that are created during the build (object files, libraries, binaries,
etc.) are placed inside that new hierarchy.

For example to build fluidity in a separate build/ directory, inside the
fluidity checkout do:

   mkdir build; cd build
   ../configure && make

You can check using "git status" that indeed no new files (other than build/)
have been created. Your fluidity executable is build/bin/fluidity.

Different branch builds can be maintained by simply creating separate build
directories for different branches. When switching branches in your checkout
git will simply ignore these untracked directories.
Instead of running make clean you can simply "rm -rf build/" (although make
clean still does the usual thing when run inside build/).
You can even run "make test" within the build/ directory. This will however
symlink build/tests to the main tests/ directory and therefore created new
files within subdirectories of it (making the test system work out-of-tree
is not really feasible). You can clean this up by running (from the top
src directory!)

  git clean -df tests/

(DON'T RUN THIS IF THERE'S ANY CHANGES IN THE tests/ DIRECTORY YOU HAVEN'T COMMITTED).
You may also have to clean the python/ directory to get rid of .pyc files.

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -24,6 +24,8 @@
 #    License along with this library; if not, write to the Free Software
 #    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
 #    USA
+VPATH = @srcdir@
+
 SHELL = @SHELL@
 
 PACKAGE_NAME = @PACKAGE_NAME@
@@ -58,7 +60,7 @@ CC	= @CC@
 CFLAGS	= @CPPFLAGS@ @CFLAGS@
 
 CXX	= @CXX@
-CXXFLAGS= @CPPFLAGS@ @CXXFLAGS@ -I./include
+CXXFLAGS= @CPPFLAGS@ @CXXFLAGS@ -I./include -I@srcdir@/include
 
 LINKER  = @LINKER@ @LDFLAGS@
 
@@ -75,7 +77,7 @@ AR = @AR@
 
 ARFLAGS	= -cr
 
-EVAL = tools/silenteval.sh
+EVAL = bin/silenteval
 
 ifeq (@MBA2D@,yes)
 LIBMBA2D = lib/libmba2d.a
@@ -83,6 +85,11 @@ endif
 ifeq (@MBA3D@,yes)
 LIBMBA3D = lib/libmba3d.a
 endif
+
+# note that in an out-of-tree build @srcdir@ != $(CURDIR)
+SPUD_PYTHON_SRC_DIR = @srcdir@/libspud/python
+SPUD_PYTHON_BUILD_DIR = $(CURDIR)/libspud/python/build
+SPUD_LIB_DIR = $(CURDIR)/lib
 
 # Thread count for make test.
 THREADS=1
@@ -140,14 +147,14 @@ lib/libvtkfortran.a:
 
 lib/libspatialindex.a:
 	@echo '    MKDIR lib'; mkdir -p lib
-	echo '    MAKE libspatialindex'; $(MAKE) -C @SPATIALINDEXDIR@ && $(MAKE) -C @SPATIALINDEXDIR@ install >> make.log 2>&1
+	@echo '    MAKE libspatialindex'; $(MAKE) -C @SPATIALINDEXDIR@ && $(MAKE) -C @SPATIALINDEXDIR@ install >> make.log 2>&1
 
 lib/libspud.a:
 	@echo '    MKDIR lib'; mkdir -p lib
-ifeq (@SPUD_ONLY@,yes)
-	echo '    MAKE libspud'; $(MAKE) -C libspud && $(MAKE) -C libspud install-libspud
-else
-	echo '    MAKE libspud'; $(MAKE) -C libspud &&  $(MAKE) -C libspud install-libspud && cd libspud/python && python setup.py build && cd ../.. && cp libspud/python/build/lib*/libspud.so python/
+	@echo '    MAKE libspud'; $(MAKE) -C libspud && $(MAKE) -C libspud install-libspud
+ifneq (@SPUD_ONLY@,yes)
+	@echo '    MAKE libspud python'; mkdir -p $(SPUD_PYTHON_BUILD_DIR) && cd $(SPUD_PYTHON_SRC_DIR) && python setup.py build_ext -b $(SPUD_PYTHON_BUILD_DIR) -t $(SPUD_PYTHON_BUILD_DIR) -L$(SPUD_LIB_DIR)
+	@cp $(SPUD_PYTHON_BUILD_DIR)/libspud.so python/
 endif
 
 libfemtools: sub_system
@@ -272,8 +279,12 @@ endif
 
 python_clean:
 	@echo "    CLEAN python"
-	@cd python; rm -rf build
-	@cd python/fluidity; find . -type l -name '*.so' -exec rm -f {} \;
+	@rm -rf python/build/
+# does not necessarily exist for out-of-tree build:
+	@if [ -d python/fluidity ]; then \
+	  cd python/fluidity; \
+	  find . -type l -name '*.so' -exec rm -f {} \;; \
+	fi
 
 .PHONY: scripts
 
@@ -323,10 +334,10 @@ endif
 	@echo "    MAKE main"
 	@cd main; $(MAKE)
 	@echo "    MAKE options_check"
-	@./tools/make_check_options.py
+	@./bin/make_check_options
 	@cd preprocessor; $(MAKE) check_options.o
 	@echo "    MAKE register_diagnostics"
-	@./tools/make_register_diagnostics.py
+	@./bin/make_register_diagnostics
 	@cd preprocessor; $(MAKE) register_diagnostics.o
 	@echo "    BUILDING fluidity_library"
 	@$(AR) $(ARFLAGS) lib/libfluidity.a \
@@ -443,12 +454,19 @@ clean: clean-light clean-test python_clean clean-debian
 	@find ./ \( -name work.pc \) -exec rm {} \;
 	@find ./ \( -name work.pcl \) -exec rm {} \;
 
+# if we're building out-of-tree there is no debian dir, so we do nothing
+# (debian package building doesn't use out-of-tree). Shouldn't this cleaning
+# happen in debian/rules actually?
 clean-debian:
-	@echo "    CLEAN debian"
-	@cd debian; rm -rf files tmp fluidity python-fluidity *.substvars *.debhelper* 
+	@if [ -d debian ]; then \
+	  echo "    CLEAN debian"; \
+	  cd debian; \
+	  rm -rf files tmp fluidity python-fluidity *.substvars *.debhelper*; \
+	fi
 
 clean-test:      
 	@echo "    CLEAN tests"
+	@if [ ! -d tests ]; then ln -s @srcdir@/tests/; fi
 	@cd tests; PYTHONPATH=../python ../tools/testharness.py --clean >/dev/null
 	@cd tests/data; $(MAKE) clean
 
@@ -501,9 +519,25 @@ distclean: clean
 test: fltools bin/$(FLUIDITY) bin/shallow_water serialtest bin/burgers_equation
 
 serialtest: fltools bin/$(FLUIDITY) bin/shallow_water
+	@if [ ! -d tests ]; then ln -s @srcdir@/tests/; fi
+	@if [ ! @srcdir@ -ef bin ]; then \
+	  if [ -e @srcdir@/bin ]; then \
+	    rm @srcdir@/bin; \
+	  fi && ln -s $(CURDIR)/bin @srcdir@/bin || { echo "*** ERROR ***: @srcdir@/bin already exists. \
+You need to remove this directory before running make test from the current build directory. \
+It will be replaced by a symlink to bin/ in the current directory."; false; } \
+	fi
 	@cd tests; ../bin/testharness -l short $(EXCLUDE_TAGS) -n $(THREADS)
 
 mediumtest: fltools bin/$(FLUIDITY) manual bin/burgers_equation bin/shallow_water spudtools
+	@if [ ! -d tests ]; then ln -s @srcdir@/tests/; fi
+	@if [ ! @srcdir@ -ef bin ]; then \
+	  if [ -e @srcdir@/bin ]; then \
+	    rm @srcdir@i/bin; \
+	  fi && ln -s $(CURDIR)/bin @srcdir@/bin || { echo "*** ERROR ***: @srcdir@ already exists. \
+You need to remove this directory before running make test from the current build directory. \
+It will be replaced by a symlink to bin/ in the current directory."; false; } \
+	fi
 	@cd tests; ../bin/testharness -l medium $(EXCLUDE_TAGS) -n $(THREADS)
 
 .PHONY: spudtools
