Revert changed to external libraries
For h5hut, libjudy, libmba2d/3d, libspud and spatialindex we only
include the source for convenience. We may make some bespoke changes but
like to stay as close as possible to upstream.

libadaptivity and libvtkfortran no longer have an upstream
and we simply treat these subdirectories as the cannonical version, so
these are still included in the pre commit hook.

diff --git a/libjudy/test/Checkit b/libjudy/test/Checkit
--- a/libjudy/test/Checkit
+++ b/libjudy/test/Checkit
@@ -47,7 +47,7 @@ exit $?
 fi
 
 #  -OR-    if Judy is installed, these can be compiled from anywhere:
-#cc -O SLcompare.c -DJUDYMETHOD      -o SL_Judy      -lJudy -lm
+#cc -O SLcompare.c -DJUDYMETHOD      -o SL_Judy      -lJudy -lm 
 #cc -O Judy1LHCheck.c                -o Judy1LHCheck -lJudy -lm
 #cc -O Judy1LHTime.c                 -o Judy1LHTime  -lJudy -lm
 echo "===  Pass: Compile of tests"
@@ -97,7 +97,7 @@ echo "   lines avg_linelen  getline   StoreD RAMused/line  store/ln lookup/ln AD
 ./SL_Judy     StringCompare.c | grep JUDY
 RET=$?
 if [ $RET -ne 0 ] ; then
-echo "===  $? Failed: JudySL if StoreD numbers are all the same"
+echo "===  $? Failed: JudySL if StoreD numbers are all the same" 
 exit $?
 fi
 echo "===  Pass: JudySL if StoreD numbers are all the same"
